// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// 直接连接地址（用于迁移和 db push）
const DIRECT_URL = process.env["DIRECT_URL"] || "postgresql://postgres:Fydw%40715@db.qkvgeuallarmbcfjzkko.supabase.co:5432/postgres";
// 连接池地址（用于应用查询）
const DATABASE_URL = process.env["DATABASE_URL"] || "postgresql://postgres.qkvgeuallarmbcfjzkko:Fydw%40715@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 应用查询使用连接池（提高性能）
    url: DATABASE_URL,
    // 迁移操作使用直接连接（db push, migrate）
    directUrl: DIRECT_URL,
  },
});
